// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateAccount(arg1) {
  return window['go']['main']['App']['ActivateAccount'](arg1);
}

export function CheckUpstreamStatus() {
  return window['go']['main']['App']['CheckUpstreamStatus']();
}

export function CreateProxy(arg1) {
  return window['go']['main']['App']['CreateProxy'](arg1);
}

export function DeleteAccount(arg1) {
  return window['go']['main']['App']['DeleteAccount'](arg1);
}

export function DeleteProxy(arg1) {
  return window['go']['main']['App']['DeleteProxy'](arg1);
}

export function GetUpstreamConfig() {
  return window['go']['main']['App']['GetUpstreamConfig']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListAccounts() {
  return window['go']['main']['App']['ListAccounts']();
}

export function ListProxies() {
  return window['go']['main']['App']['ListProxies']();
}

export function QuitApplication() {
  return window['go']['main']['App']['QuitApplication']();
}

export function RefreshAccountUsage() {
  return window['go']['main']['App']['RefreshAccountUsage']();
}

export function SaveUpstreamConfig(arg1) {
  return window['go']['main']['App']['SaveUpstreamConfig'](arg1);
}

export function SetProxyEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetProxyEnabled'](arg1, arg2);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function StartOpenAIAuth() {
  return window['go']['main']['App']['StartOpenAIAuth']();
}

export function UpdateProxy(arg1) {
  return window['go']['main']['App']['UpdateProxy'](arg1);
}
